image: ubuntu/21.10
oauth: pages.sr.ht/PAGES:RW
environment:
  site: paveloom.srht.site
tasks:
  - build: |
      cd $site
      .github/scripts/github/build.bash https://paveloom.srht.site/
  - package: |
      cd $site
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
