image: paveloom/site
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
variables:
  GIT_DEPTH: 0
pages:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - scripts/build.bash https://paveloom-g.gitlab.io/personal/site
  artifacts:
    paths:
      - public
