image: ubuntu:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - scripts/build.bash https://paveloom-g.gitlab.io/personal/site/
  artifacts:
    paths:
      - public
