image: paveloom/site
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
variables:
  GIT_DEPTH: 0
pages:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - |
      scripts/build.bash \
        https://paveloom-g.gitlab.io/personal/site \
        https://gitlab.com/paveloom-g/personal/site
  artifacts:
    paths:
      - public
