image: ubuntu:21.10

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - .github/scripts/github/build.bash https://paveloom-g.gitlab.io/personal/site
  artifacts:
    paths:
      - public

      