image: ubuntu:21.10

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH

test:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - .github/scripts/github/build.bash https://paveloom.gitlab.io/

pages:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - .github/scripts/github/build.bash https://paveloom.gitlab.io/
  artifacts:
    paths:
      - public

      