when:
  - event: push
    branch: master
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      partial: false
steps:
  build:
    image: paveloom/site
    secrets: [mail, token]
    commands:
      # Build the site
      - |
        scripts/build.bash \
          https://paveloom.codeberg.page \
          https://codeberg.org/paveloom/pages/src/branch/master
      # Configure Git
      - git config --global user.email $MAIL
      - git config --global user.name "Pavel Sobolev"
      - git clone -b pages https://$TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      # Copy the site to the local `pages` branch
      - cd $CI_REPO_NAME
      - cp -r ../public/* .
      # Rewrite the latest commit of the remote `pages` branch
      - git add -A
      - git commit --fixup $(git rev-list HEAD | tail -n 1)
      - |
        GIT_SEQUENCE_EDITOR=: git rebase -i --autosquash --root pages
      - git push -f origin pages
