name: paveloom-dev
services:
  site:
    build: .
    develop:
      watch:
        - path: src
          action: rebuild
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
networks:
  traefik:
    external: true
