name: paveloom-dev
services:
  site:
    build:
      context: .
      args:
        BASE_URL: ${BASE_URL:-}
    image: ghcr.io/paveloom/site:latest
    develop:
      watch:
        - path: .
          action: rebuild
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
networks:
  traefik:
    external: true
