base_url = "https://paveloom.dev"

title = "paveloom's digital garden"
description = "A personal digital garden about all kind of stuff!"

default_language = "en"

compile_sass = true

author = "Pavel Sobolev"

build_search_index = true

[markdown]
highlight_code = true

[slugify]
paths = "off"
taxonomies = "off"
anchors = "off"

[search]
include_title = true
include_description = true
include_date = false
include_path = false
include_content = true
index_format = "fuse_json"
