base_url = "https://paveloom.dev"

title = "paveloom's digital garden"
description = "A personal digital garden about all kind of stuff!"

compile_sass = true

[markdown]
highlight_code = true

[slugify]
paths = "off"
taxonomies = "off"
anchors = "off"
