base_url = "https://paveloom.dev"

title = "paveloom's notes"
description = "A personal collection of notes"

default_language = "en"

compile_sass = true

minify_html = true

author = "Pavel Sobolev"

build_search_index = true

[markdown]
lazy_async_image = true

[markdown.highlighting]
error_on_missing_language = true
style = "class"
light_theme = "light"
dark_theme = "dark"
extra_themes = [ "themes/light.json", "themes/dark.json" ]

[slugify]
paths = "off"
taxonomies = "off"
anchors = "off"

[search]
include_title = true
include_description = true
include_date = false
include_path = true
include_content = true
index_format = "fuse_json"
