site_name: ~/paveloom
site_description: An odd fellow steaming some code
site_author: Pavel Sobolev
docs_dir: content
site_dir: public
repo_name: Source code
theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.svg
  logo: assets/favicon.svg
  font: false
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.share
    - search.suggest
    - toc.follow
copyright: |
  <span style="color: var(--md-footer-fg-color--lighter)">Authored by</span> Pavel Sobolev
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://paveloom.dev
      name: Main
    - icon: fontawesome/solid/bolt
      link: https://paveloom.on.fleek.co
      name: Fleek
    - icon: simple/codeberg
      link: https://paveloom.codeberg.page
      name: Codeberg
    - icon: simple/github
      link: https://paveloom.github.io
      name: GitHub
    - icon: simple/gitlab
      link: https://paveloom-g.gitlab.io/personal/site
      name: GitLab
    - icon: simple/rss
      link: https://github.com/paveloom/paveloom.github.io/commits/master.atom
      name: RSS
extra_css:
  - assets/extra.css
extra_javascript:
  - assets/shortcuts.js
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - smarty:
      smart_angled_quotes: true
  - toc:
      permalink: "#"
plugins:
  - blog:
      archive: false
      categories: false
      pagination: false
      post_excerpt_separator: <!-- separator -->
      post_url_format: "{slug}"
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true
      exclude:
        - blog/*.md
        - journal/README.md
        - pensieve/README.md
  - literate-nav:
      nav_file: sitemap.md
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      js_files:
        - assets/shortcuts.js
      css_files:
        - assets/extra.css
  - section-index
