site_name: ~/paveloom
site_description: "@paveloom's website"
site_author: Pavel Sobolev
site_url: https://paveloom.github.io
docs_dir: content
site_dir: public
theme:
  name: material
  favicon: assets/favicon.svg
  logo: assets/favicon.svg
  font: false
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to the dark theme
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to the light theme
extra_css:
  - assets/extra.css
markdown_extensions:
  - toc:
      permalink: "#"
plugins:
  - search:
      min_search_length: 1
      prebuild_index: true
