name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: paveloom/site
    steps:
      - name: Checkout the repository
        run: |
          git clone https://${{ secrets.GITHUB_TOKEN }}@codeberg.org/$GITHUB_REPOSITORY.git .
      - name: Build the site
        run: |
          git checkout master
          scripts/build.bash \
            https://paveloom.codeberg.page \
            https://codeberg.org/paveloom/pages/src/branch/master
      - name: Deploy the site
        run: |
          git checkout -f pages
          find -mindepth 1 -maxdepth 1 ! -name public ! -path './.git*' -exec rm -r {} \;
          cp -r public/* .
          git add -A
          git config user.email paveloom@riseup.net
          git config user.name "Pavel Sobolev"
          git commit --fixup $(git rev-list HEAD | tail -n 1)
          GIT_SEQUENCE_EDITOR=: git rebase -i --autosquash --root pages
          git push -f origin pages
