[book]
title = "Pensieve"
authors = ["Pavel Sobolev"]
description = "A snapshot of @paveloom's knowledge"
language = "en"
hellothere = "test"

[build]
build-dir = "../book"

[output.html]
preferred-dark-theme = "ayu"
no-section-label = true
site-url = "/pensieve/"

[output.html.print]
enable = false

[output.html.fold]
enable = true

[output.linkcheck]
optional = true
