name: Build Image
on:
  push:
    branches:
      - master
jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: paveloom-site
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build the image
        run: |
          nix build -v .#image
          ls -l result
      - name: Upload the image
        run: |
          skopeo login --username paveloom --password "${{ secrets.DOCKER_HUB_AUTH_TOKEN }}" docker.io
          skopeo copy oci-archive://$(readlink -f result) docker://paveloom/site:latest
