name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build the site
        uses: docker://paveloom/site
        with:
          args: |
            sh -c "\
              scripts/build.bash \
                https://paveloom.github.io \
                https://github.com/paveloom/paveloom.github.io"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          single-commit: true
