name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  BuildAndDeploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Build the site
      run: scripts/build.bash https://paveloom.github.io/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: public
        single-commit: true
